### ISSUE TITLE
Alternative distribution formats

### ISSUE THREAD

**Issue by FoxBlocks** [tom-james-watson/Emote#11]
Currently I have Snap installed just for this application, so it would be nice if I could install Emote via APT or a .deb package instead and uninstall Snap.

**Comment by tom-james-watson** [comment]
No plans at the moment, no.

I've tried packaging debs and managing ppas before and it was a bit of a nightmare. Snap is comparison was waaaay easier to set up. That, plus a single package that works on pretty much any platform and built-in auto-updating made it a pretty easy choice.

If somebody wants to provide a pull request for packaging up a deb, I'm not against it. 

I'd also be interested in knowing what would be involved in / accepting PRs setting up flatpak support.

**Comment by ItzMichaelPhillips** [comment]
Bummer. Okay, thanks for the quick response.

**Comment by lkrms** [comment]
Thanks so much for your work on Emote -- I've just got it working on Arch and it fills a gap I've been trying to fill for quite a while. A flawless app so far :smiley: 

As for packaging, I understand the advantages of snaps (convenience for developers and users; easier updates; fewer dependency issues; built-in AppArmor-based sandboxing), but they also come with some significant costs, like:

- bandwidth and storage bloat (Emote goes from 84kB to 65MB once dependencies are rolled in--that adds up fast with hundreds of packages)
- resource consumption and system latency (`snapd` running continuously is problematic, but then there's the cost of creating, destroying and operating within sandboxes)
- loss of privacy (not that Canonical is tooooo offensive in this area, but that's only because other players are so much worse)

Obviously I won't be installing snapd here, but thankfully not many patches were required to package Emote for Arch Linux, so there shouldn't be a lot of refactoring involved in supporting other packaging systems. Here's the [emote AUR package](https://aur.archlinux.org/packages/emote/) I put together today, and here's what it does:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emote

`setuptools` are used for some additional steps, so [setup.py](https://aur.archlinux.org/cgit/aur.git/tree/setup.py?h=emote) had to be expanded a little, but otherwise it was pretty straightforward.

**Comment by tom-james-watson** [comment]
Nice, looks good. I haven't got an arch install to try it out, though. I'm not going to support AUR package myself but I'm happy for somebody else to package it up.

Realistically the only other package I would be interested in supporting myself is flatpak.

**Comment by lkrms** [comment]
> Nice, looks good, thanks! I haven't got an arch install to try it out, though. I'm not going to support AUR package myself but I'm happy for somebody else to package it up.

All good, I'm getting notified of new releases and will maintain the AUR package :+1:

**Comment by rafaelmardojai** [comment]
I'm interested in creating a Flatpak, but the files structure seems very Snap specific. 

Have you considered using [meson](https://mesonbuild.com/) for building? 
Moving the icon and `.desktop` to a common `data` folder?
Installing the `static` files as [GResources](https://developer.gnome.org/gio/stable/GResource.html)?

**Comment by tom-james-watson** [comment]
Correct me if I'm wrong, but meson does not seem to support building python programs?

**Comment by rafaelmardojai** [comment]
> Correct me if I'm wrong, but meson does not seem to support building python programs?

Yes it does, there's plenty of Python/GTK apps using it.

I would send a PR, but I have zero experience with snap, and I wouldn't be able to update the manifest to the changes.

**Comment by zicklag** [comment]
I've not got time to work on it, but just wanted to bring up that I would totally use a flatpak. I'm not root on my machine so flatpak is a big win over snap which requires root access.

**Comment by prcr** [comment]
I also came here looking for an alternative distribution. :slightly_smiling_face: Flatpak would work for me as well! :+1:

**Comment by Adrian-Grimm** [comment]
I'm using Flatpak as well - pop!OS supports it out of the box. I don't like snap because the server is a central closed system.
Debian package would also be nice.

**Comment by daholzfeind** [comment]
Are there any updates regarding flatpak? I cannot install it because i do not want to use snaps on my laptop. Please consider flatpak support.

**Comment by tom-james-watson** [comment]
No, there are no updates. I'm open to PRs.

**Comment by yllekz** [comment]
Following as I'm interested in a Flatpak version of this. Really want to get away from Snap.

**Comment by 266-750Balloons** [comment]
Packaging is getting a lot more convenient. Manimpango got into the Debian repositories in June, so it should at least be easily packagable for Debian Testing. I also found that emote works just fine with the default Python runtime (3.10) and the latest versions of all required libraries. A makefile just needs to be written to copy some files to the right place, and maybe a patch to use the Noto Color emoji font from the Debian package rather than a static file.

**Comment by UnderEu** [comment]
+1 for Flatpak or, preferably, DEB package support - Snaps on my system has became such a piece of garbage experience because reasons not related to your app that I'm in ditching snap support completely and this one is the last app remaining to complete the transition.

**Comment by KaKi87** [comment]
+1, I'm currently downloading this app at 169 KB/s using `snap`, despite having a 110 MB/s connection.

**Comment by tom-james-watson** [comment]
Please just use the emoji reactions instead of adding `+1` comments.

**Comment by KaKi87** [comment]
Well, it's been 2 and a half years since this issue was created so I thought commenting could boost it better than just silently adding a reaction.

**Comment by tom-james-watson** [comment]
If you want to see this implemented then PRs are of course welcome.

**Comment by vemonet** [comment]
Hi everyone and @tom-james-watson , I just added flatpak support in this PR: https://github.com/tom-james-watson/Emote/pull/89

The only thing that does not work is the built-in `ctrl + alt + e` keybinding to invoke Emote, but that can be easily worked around using a custom keybinding. Otherwise everything else seems to work fine, and starting time feels faster and more consistent (cf. the PR for more details)

We will be thankful if some people interested in having Emote as a flatpak could try it on their system and let us know if it works as expected! (especially for desktop environments other than GNOME)

**Comment by KaKi87** [comment]
> We will be thankful if some people interested in having Emote as a flatpak could try it on their system

With pleasure, what's the install command ?

> especially for desktop environments other than GNOME

I have Cinnamon (Linux Mint 21) and Unity (Ubuntu 22.04) here.

**Comment by vemonet** [comment]
Thanks, everything is in the readme in my fork (you will need to do all of this from my fork): https://github.com/vemonet/Emote#%EF%B8%8F-packaging-with-flatpak

**Comment by alexanderadam** [comment]
@vemonet nice, are you considering a PR?

**Comment by KaKi87** [comment]
> you will need to do all of this from my fork

Sorry I thought you'd have packaged it for testing already.

> are you considering a PR?

Read again.

**Comment by vemonet** [comment]
@alexanderadam  the fork has been share 2 messages above, not sure how you missed it :)

@KaKi87 can I do this? To share a pre-built version to test easily? (how if possible?)

At the moment, I am waiting for the PR to be merged to create the entry in flathub, so we do it with the main repository and ideally make it "verified"

Otherwise to try it should not be too heavy, you will need to run 2 commands after cloning the fork:

```bash
git clone --branch=add-flatpak https://github.com/vemonet/Emote
cd Emote
# install build dependencies with flatpak:
make flatpak-install
# build and run emote locally, should take less than a minute:
make flatpak
```

Note that I just also just updated the list of emojis (adding recent emojis like 🫠 🫴), and disabled a list of blocked emojis that were not working on snap apparently (hair stylist, and transgender  folks should be happy! 👨‍🦲🧑‍🦰🏳️‍⚧️). 

They are all working in the flatpak package, adding a few dozen (maybe even hundreds?) new emojis!

Also Emote is properly showing in GNOME software GUI when installed, with reviews automatically retrieved. And apparently it's the best noted emoji picker with 4.4 for 35 reviews, but still ex aequo with Smile (which has 20 reviews) :) so feel free to give it some love!

**Comment by tom-james-watson** [comment]
Amazing work by @vemonet! I've added some comments on the PR but they all look solvable. It looks like in the end we not only will be adding support for flatpak, but we'll actually be dropping support for snap entirely. That's unless someone wants to step up and work out how to upgrade to the latest core snap etc. to unblock a whole bunch of things like not being able to update the emoji list.

Hopefully we'll have this all merged and officially published soon :rocket:

**Comment by sonjoonho** [comment]
Ah just seen this thread – I have a PR that upgrades the base Snap to core22. If there are no problems then I think it makes sense to offer two alternative distribution formats, but I'm also fine to ditch the PR and remove Snap support.

**Comment by tom-james-watson** [comment]
As of version 4.0.0, Emote is now available as a Flatpak - https://flathub.org/apps/com.tomjwatson.Emote.
