### ISSUE TITLE
emoji not displaying

### ISSUE THREAD

**Issue by samsch** [tom-james-watson/Emote#128]
OS: Xubuntu 22.04 (LTS)
Package: both flatpak and ubuntu repo snap.
Version: Snap version 4.0.1 (I believe it started with 4.0.0), and flakpak just says "dev build"

![image](https://github.com/tom-james-watson/Emote/assets/10436679/a8b1d6ef-addc-439c-9ed7-3198160731ee)

I have an emoji font installed (Noto Color Emoji), and this `~/.config/fontconfig/fonts.conf `
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
(I'm not actually sure if that config even does anything, but I did also remove it and run fc-cache, and that made no difference to the problem at hand.)
Otherwise with respect to font handling the system is pretty vanilla, except for a short list of additionally installed fonts (none of which are set as defaults anywhere or are emoji fonts).

**Comment by samsch** [comment]
Solved!
Hint came from https://github.com/mijorus/smile/issues/30 as smile also suffered the same issue.

Ubuntu released an update in February to the fonts-noto-color-emoji package, and it seems like some type of default system config may have been included that disrupted alternate installations of the emoji font package.

The solution was to remove/uninstall my existing manually installed noto color emoji from my system and delete the `~/.config/fontconfig/fonts.conf` file, then install the ubuntu package `sudo apt install fonts-noto-color-emoji`.

**Comment by erincerys** [comment]
@samsch This helped me with an issue I was having on Arch where launching was slow, and emoji search had been _extremely_ slow when entering a single character. It turns out there was old conflicting fonts in `/usr/share/fonts/noto-color-emoji/` which were not owned by any package, when the `noto-fonts-emoji` package presently installs to `/usr/share/fonts/noto/`. Removing the former files addressed both issues that had plagued me for months! Thanks for posting your followup, truly!!
