### ISSUE TITLE
Search individually on each word of an emoji name to improve search

### ISSUE THREAD

**Issue by afv** [tom-james-watson/Emote#17]
Hi! 😀

How is the search done?
When searching for "shr", only "shrimp" appears, and "man_shrugging" is missing.

![image](https://user-images.githubusercontent.com/1532245/95617540-838c9280-0a63-11eb-8b73-d256714a574d.png)

![image](https://user-images.githubusercontent.com/1532245/95617572-8d15fa80-0a63-11eb-9867-2e9d80a6f706.png)

Searching for "man " (with a space) returns nothing:

![image](https://user-images.githubusercontent.com/1532245/95617631-a3bc5180-0a63-11eb-9190-ae5f903df40b.png)

On the other hand (and it is OK), searching for "laugh" makes "rofl" appear (which has no "laugh" in the name?):

![image](https://user-images.githubusercontent.com/1532245/95617487-6ce63b80-0a63-11eb-93bd-c6d1c0d19e37.png)

Thanks!

**Comment by tom-james-watson** [comment]
The code will search for matches on the emoji name, e.g. `man_shrugging`, or any of its keywords, e.g. `["man", "male", "boy", "confused", "indifferent", "doubt"]`. We check for a match with `startsWith`, to only match from the start of the word, which avoids a lot of false positives that look like noise.

I've realised what we need to do is to split up the emoji name so that we search individually on each word of the name, so in this case on both `man` and `shrugging`. That should fix it! Will get on that soon.

**Comment by afv** [comment]
Thanks! 😀

[Element web](https://github.com/vector-im/element-web) has a very nice emoji picker. Some features I like about it, that could be a suggestion for Emote:

- search results grouped by category
- status bar with hovered emoji details (no need for waiting for a tooltip)
- continuous scroll between categories


Search example:

![Element_Emoji_Picker](https://user-images.githubusercontent.com/1532245/95744813-e06a9180-0c8b-11eb-9e17-c6797ca87cbe.png)

![Element_Emoji_Picker_notes](https://user-images.githubusercontent.com/1532245/95744821-e2cceb80-0c8b-11eb-9d41-4b0108b9dc06.png)

Scroll example:

![2020-10-12_13-12-03_Element_emoji_picker](https://user-images.githubusercontent.com/1532245/95745517-207e4400-0c8d-11eb-8ef8-6d225a640e0c.gif)

**Comment by tom-james-watson** [comment]
Yeah agreed - those are all really nice. Will consider looking into their implementation more. I suspect at some point I'll do a bit of an overhaul with libhandy / GTK4.

**Comment by tom-james-watson** [comment]
Released in 1.1.0 :+1:
