### ISSUE TITLE
Python 3.9 issue?

### ISSUE THREAD

**Issue by victoriastuart** [tom-james-watson/Emote#22]
```bash
$ date
Fri Dec 18 03:11:25 PM PST 2020

$ yay -Ss emote | grep -w emote
aur/emote 1.0.1-2 (+2 0.74) (Installed)

$ which emote
/usr/bin/emote

$ emote
Traceback (most recent call last):
  File "/usr/bin/emote", line 33, in <module>
    sys.exit(load_entry_point('Emote==1.0.1', 'gui_scripts', 'emote')())
  File "/usr/bin/emote", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Emote

$ python --version
Python 3.9.1

$ uname -a
Linux victoria 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
```

**Comment by tom-james-watson** [comment]
I don't actually maintain the arch package so can't really help you, I'm afraid. Pinging @lkrms, who is who created it.

**Comment by lkrms** [comment]
Thanks for tagging me, @tom-james-watson.

I haven't had a chance to get into it yet, but it seems to be a similar issue to [this](https://github.com/pyinstaller/pyinstaller/issues/4258) and [this](https://gitlab.com/python-devs/importlib_metadata/-/issues/71), i.e. related to metadata that `importlib_metadata` can't auto-discover (presumably because it's absent). I'm not sure if this is an issue within Emote or a packaging issue, but I'll let you know what I find out.

@victoriastuart, as per my AUR comment a few minutes ago, rebuilding the package fixes the error (until the next dependency update breaks it again, but hopefully we'll have it patched before then).

**Comment by victoriastuart** [comment]
Mentioned AUR package: https://aur.archlinux.org/packages/emote/

**Comment by lkrms** [comment]
Just to follow up:

As best I can tell, this issue is the result of a bug in Python setuptools that's been fixed, but if it re-surfaces I'll investigate further.
