### ISSUE TITLE
Update Emoji font to unicode 14.

### ISSUE THREAD

**Issue by rago666** [tom-james-watson/Emote#57]
Noto Color emoji has been updated to version 14. 
[Release Tag](https://github.com/googlefonts/noto-emoji/releases/tag/v2.034)

**Comment by tom-james-watson** [comment]
We are sourcing the emojis data from https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv and it looks like they need to implement all of their own emoji designs before the new emojis make it into the data file: https://github.com/hfg-gmuend/openmoji/issues/344.

There are two that have already been added: https://emojipedia.org/biting-lip/ and https://emojipedia.org/bubbles/, which will go out in emote 3.1.0 at least.

I didn't realise that emoji releases would be delayed like this, so it might be better to actually just curate our own data file instead of depending on third parties. That's extra work that right at the moment I personally don't have time to do, though.

**Comment by CutestNekoAqua** [comment]
looks like most of unicode 14 is now in https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv ☺

**Comment by pleshevskiy** [comment]
I have an issue that some emoji are copied with some garbage
![image](https://user-images.githubusercontent.com/7839004/191491408-85bc0bea-b785-4468-a1e9-0a4eaaecb770.png)

Maybe this is related 🤔

**Comment by wezm** [comment]
@pleshevskiy if you mean the `<fe0f>` that's not garbage it's an emoji variation selector. Some Unicode code points pre-date emoji and default to a non-emoji representation (black and white). When they're followed by the emoji variation selector it's an instruction to the text layout engine to use the emoji representation. Unfortunately not all terminals have the sophisticated text layout machinery for this to work property. 

https://unicode-table.com/en/FE0F/
http://unicode.org/faq/vs.html

**Comment by pleshevskiy** [comment]
@wezm thank you! didn't know about that
