### ISSUE TITLE
Kaomoji Support

### ISSUE THREAD

**Issue by Xeronel** [tom-james-watson/Emote#70]
Is it possible to add support for kaomoji similar to the picker in Windows?  

![Screenshot_2022-05-19_233636](https://user-images.githubusercontent.com/3720649/169446665-4ba676cd-4de0-4b3f-9999-23de307f4e2d.png)

**Comment by carbongreat13** [comment]
I think it should be simple according to Unix culture.
I am against supporting kaomoji.

**Comment by tom-james-watson** [comment]
I agree with @carbongreat13. At least for now I don't want to make the app any more complex.

**Comment by joaociocca** [comment]
Linux folks are a curious bunch... "we want more users" x "we don't want to add stuff that could attract more users"
I really liked Emote. Every now and then I use some Linux distro as my main for a while (I use others to work almost all the time). Last night I installed Pop. But I found myself missing Windows 10's emoji picker. Emote is the one most close to it, and despite it taking a bit lag to open the popup, putting `emote` as GNOME shortcut for <super+.> works just like it...
But now, I find myself missing the kaomoji from there - mostly ¯\_(ツ)_/¯ and (╯°□°)╯︵ ┻━┻, but that's me, I bet other people love using different ones and that could be a reason why Microsoft added a whole tab of it there.

So, ok, I can understand the "don't want to make the app more complex", but if you're appealing to the "against it because Unix culture", I do wonder how evolution would work if everyone wanted everything to stay the same. What would be the point of improving things, you know?

**Comment by tom-james-watson** [comment]
This is an open source project that I developed by myself and shared with the world for free. You are free to develop your own fork, you are free to make a pr adding the functionality.

Please check your entitlement. Open source developed owe you exactly nothing.

**Comment by joaociocca** [comment]
I might have gotten a wee bit enraged by the conversativeness of the thing, and I apologize for that. As I've said, your project is awesome and the "don't want to make it more complex" argument is valid and solid. If I failed to do so before: thanks for this and kudos.

**Comment by tom-james-watson** [comment]
No worries, thanks for that :)

**Comment by joaociocca** [comment]
one possibility here... altough I totally lack knowledge of how it currently is... but maybe the app could have a functionality for people to add their own stuff? like, I now people who end up memorizing UTF codes to right alt+code it because they use it so much. I think it'd be a lot easier to implement using a single character/emoji (like the TM or the Euro symbols, for example), but perhaps it could be extended to multiple characters so people could add kaomojis on their own as they want/use it
