### ISSUE TITLE
U+1F5FF is not a moai🗿

### ISSUE THREAD

**Issue by carbongreat13** [tom-james-watson/Emote#73]
U+1F5FF is a emoji of a [moyai](https://ja.wikipedia.org/wiki/%E3%83%A2%E3%83%A4%E3%82%A4%E5%83%8F) in [Shibuya](https://en.wikipedia.org/wiki/Shibuya), Japan. It is not a emoji of the [moai of Easter Island](https://en.wikipedia.org/wiki/Moai).

**Comment by carbongreat13** [comment]
https://en.wikipedia.org/wiki/Shibuya#Sightseeing_and_historic_sites
> On the southwest side of Shibuya station, there is another popular meeting place with a statue called "Moyai". The statue resembles a Moai statue, and it was given to Shibuya by the people of Niijima Island in 1980.

**Comment by tom-james-watson** [comment]
Emoji data is sourced from https://github.com/hfg-gmuend/openmoji (https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.csv). I'd prefer not to override their data, so I'd recommend opening an issue there instead.

"moyai" is one of the aliases, so it would appear when searching for it anyway.

**Comment by waldyrious** [comment]
Actually, this part of the data is not part of OpenMoji's custom tags/aliases; it is sourced from https://github.com/milesj/emojibase (see [here](https://github.com/milesj/emojibase/blob/49fe5f91fb770b84062f1fadc3af8c3ad789254c/packages/generator/src/resources/shortcodesLegacy.ts#L1180)), which in turn imports it directly from Unicode. In particular, this character is included in Unicode's Emoji table [with the short name "moai"](https://unicode.org/emoji/charts-14.0/full-emoji-list.html#1f5ff), and its [keywords in Unicode's CLDR](https://github.com/unicode-org/cldr/blob/8a2f6208afd5108fba045f7b4819f1c097ca0781/common/annotations/en.xml#L3361) are "face | moai | moyai | statue".

Emojipedia also [suggests](https://emojipedia.org/moai/) that although the origin of the emoji may have been the Moyai Statue near Shibuya, the current usage is broadly/internationally understood as representing the Easter Island moai statues.

That's to say that (1) if this is to be fixed, it should be taken up in Unicode's CLDR, and flow downstream from there; and (2) it's likely that the interpretation as the Easter Island statues (rather than the specific landmark inspired by them) has been intentionally upheld, since the moai statues are the older and more broadly known concept.

**Comment by tom-james-watson** [comment]
Yeah, agreed. To me it's always been the Easter Island statues at least!
