### ISSUE TITLE
Allow continuously navigating the table

### ISSUE THREAD

**Issue by waldyrious** [tom-james-watson/Emote#82]
Currently I can use the arrow buttons to move in any direction of the emoji grid. However, when I reach the end of a row, I'd like to be able to keep pressing the <kbd>→</kbd> key and have the focus change to the first entry of the next row (and the same behavior, in reverse, when pressing the <kbd>←</kbd> key).

**Comment by tom-james-watson** [comment]
I agree that would be nice. With the way these gtk widgets work though, I don't think it would be viable to actually implement that nicely. If I were building this in react or something then it would be 100x easier. Maybe we can look at this after upgrading to gtk4 (https://github.com/tom-james-watson/Emote/issues/90).

**Comment by Sylvain303** [comment]
@waldyrious 

I open the discussion of the preferred behavior we could implement.

See cross link issue above ⬆️

> When I reach the end of a row, I'd like to be able to keep pressing the → key and have the focus change to the first entry of the next row (and the same behavior, in reverse, when pressing the ← key).

Personally, I would keep cycling the **same** line, instead of also incrementing to the next row (down).

If I manage to perform what I suggested that would require 2 keys to achieve your wish: ➡️ + ⬇️

➡️ (at end, right most of the row) go back to the start of the same line
⬇️ actual `Gtk.Grid` behavior next row (down) in the grid (also other GUI element)

What about edge use-case, scenario? 
1. first column, on first row
2. last column on last row

## scenario: history popup navigation

History is first view, displayed.
I want 👌

![image](https://github.com/tom-james-watson/Emote/assets/274026/5095aafa-c2f9-45fd-b1fa-b9cd392d08b1)

Actually I need to perform:
1. ⬇️ going from   `search` to first row left most emoji
2. ➡️➡️➡️➡️ many time to go to the end

with my suggested change a single ⬅️ would bring me to the correct emoji (which will move in the history as being the most recently used)

Note: we could also imagine a setting to implement both algorithms, obviously. User will chose the one he or she prefers. 😉 (much more code to write)  

Please give some feedback and feel on some scenario and corner cases.
