### ISSUE TITLE
Copy Emoji and auto paste it 

### ISSUE THREAD

**Issue by Noxmiles** [tom-james-watson/Emote#84]
Similar, but not the same, as #81 

Please add an option (in the settings) for auto copy & paste after selecting an emoji.

Like, close the GUI and so getting focus back on the old window and then auto-paste the emoji.

**Comment by tom-james-watson** [comment]
This is how the app works under X11 and  the fact that it doesn't under Wayland is due to intentional design limitations in Wayland. See the message near the top of the readme: https://github.com/tom-james-watson/Emote#-emote.

I am not aware of any way of achieving this on a system that uses Wayland.
